name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: Build icons
        run: npm run build:icons

      - name: Test
        run: npm run test
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Percy Test
      #   if: github.base_ref == 'master' || github.ref == 'refs/heads/master'
      #   run: 'npm run test:visual'
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Replace images
        if: github.ref == 'refs/heads/master'
        run: gulp replaceImagePaths --imagesDir="https://www.middlebury.edu/office/themes/custom/middlebury_theme/images/"

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          publish_branch: master-dist
          github_token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'master'
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Frontend build
          fields: repo,commit,message,author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
